//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemestrProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atla()
        {
            this.Moje_rosliny = new HashSet<Moje_rosliny>();
            this.Nawozenies = new HashSet<Nawozenie>();
            this.Podlewanies = new HashSet<Podlewanie>();
        }
    
        public string nazwa { get; set; }
        public string stanowisko { get; set; }
        public string podlewanie { get; set; }
        public bool domowa { get; set; }
        public bool ogrodowa { get; set; }
        public string nawozenie { get; set; }
        public string choroby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moje_rosliny> Moje_rosliny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nawozenie> Nawozenies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Podlewanie> Podlewanies { get; set; }
    }
}
