//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemestrProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choroby
    {
        public int id { get; set; }
        public string nazwa_choroby { get; set; }
        public string leczenie { get; set; }
        public string skutki_choroby { get; set; }
        public string jakich_roslin_dotyczy { get; set; }
    }
}
