//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemestrProjekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GardenManagementDBEntities : DbContext
    {
        public GardenManagementDBEntities()
            : base("name=GardenManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atla> Atlas { get; set; }
        public virtual DbSet<Choroby> Chorobies { get; set; }
        public virtual DbSet<Moje_rosliny> Moje_rosliny { get; set; }
        public virtual DbSet<Nawozenie> Nawozenies { get; set; }
        public virtual DbSet<Podlewanie> Podlewanies { get; set; }
    }
}
