//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemestrProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moje_rosliny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Moje_rosliny()
        {
            this.Nawozenies = new HashSet<Nawozenie>();
            this.Podlewanies = new HashSet<Podlewanie>();
        }
    
        public string imie { get; set; }
        public string nazwa { get; set; }
        public Nullable<System.DateTime> ostatnie_podlewanie { get; set; }
        public Nullable<System.DateTime> ostatnie_nawozenie { get; set; }
        public string przebyte_choroby { get; set; }
    
        public virtual Atla Atla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nawozenie> Nawozenies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Podlewanie> Podlewanies { get; set; }
    }
}
