//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemestrProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podlewanie
    {
        public int id { get; set; }
        public string imie { get; set; }
        public string nazwa { get; set; }
        public Nullable<System.DateTime> data_pierwszego_podlania { get; set; }
    
        public virtual Atla Atla { get; set; }
        public virtual Moje_rosliny Moje_rosliny { get; set; }
    }
}
